project:
  type: book
  output-dir: docs


book:
  title: "Lab Materials for an Introduction to Biostatistics"
  author: "Mike Whitlock (original material), Chris Muir (modifications), Andy Rominger (modifications and web design), Renata Diaz (web design)"
  date: "12/20/2023"
  chapters:
    - index.qmd
comments:
  hypothesis: true


bibliography: references.bib


format:
  html:
    theme: cosmo



