project:
  type: book
  output-dir: docs


book:
  title: "Labs for Intro Biostatistics"
  author: "Mike Whitlock (original material), Chris Muir (modifications), Renata Diaz (web design)"
  chapters:
    - index.qmd
    - lab01.qmd
    - lab02.qmd
comments:
  hypothesis: true


bibliography: references.bib


format:
  html:
    theme: 
      - cosmo
      - mods.scss



