project:
  type: book
  output-dir: docs


book:
  title: "Labs for Intro Biostatistics"
  author: "Mike Whitlock (original material), Chris Muir (modifications), Andy Rominger (modifications and web design), Renata Diaz (web design)"
  chapters:
    - index.qmd
    - lab01.qmd
    # - lab02.qmd
    # - lab03.qmd
    # - lab04.qmd
    # - lab05.qmd
    # - lab06.qmd
    # - lab07.qmd
    # - lab08.qmd
    # - lab09.qmd
    # - lab10.qmd
    # - lab11.qmd
    # - lab12.qmd
    # - lab13.qmd
    # - lab14.qmd
comments:
  hypothesis: true


bibliography: references.bib


format:
  html:
    theme: 
      - cosmo
      - mods.scss



