project:
  type: book
  output-dir: docs


book:
  title: "Labs for Intro Biostatistics"
  chapters:
    - index.qmd
    - lab01.qmd
    - lab02.qmd
    # - lab03.qmd
    # - lab04.qmd
    # - lab07.qmd
    # - lab08.qmd
    # - lab09.qmd
    # - lab10.qmd
    # - lab12.qmd
    # - lab11.qmd
    # - lab15.qmd
    # - lab13.qmd
    # - lab16.qmd
    # - lab17.qmd
comments:
  hypothesis: true


bibliography: references.bib


format:
  html:
    theme: 
      - cosmo
      - mods.scss



