# Theory and motivation of process modeling

## Key questions

1. What is a process modeling approach?
1. What kinds of questions can process models explore (that other methods cannot)?
1. What are the limitations or constraints of process modeling?

## Lesson objectives

After this lesson, learners should be able to...

1. Describe what defines a process model.
1. Evaluate the advantages and limitations of a process modeling approach.
1. Generate questions in ecology and evolution that could be addressed using process modeling.
1. Understand the unified neutral theory of biodiversity as an example of a well-established process model in ecology.

## Lesson outline

[Slides](slides/day1_slides.pdf)

Video lectures:


1. [Theory and motivation of process modeling](https://youtu.be/s6RwgGlIop8)
2. [The Unified Neutral Theory of Biodiversity as a process model](https://youtu.be/fuijMa_hTwo)
3. [Video on playing neutral theory as a game, and in R](https://www.youtube.com/watch?v=P0llru92YsU)


### (Lecture + discussion) What do we _mean_ by process modeling, anyway?

Key points:

1. In a process model, we play a "game", with a set of entities following a system of defined rules, and see how the outcomes of the game vary as we change the rules. 
1. These models are often nondeterministic and often do not have closed-form, analytical solutions. 

### (Lecture + discussion) What are the applications of process modeling for eco-evo?

Key points:

1. A process model offers almost unlimited flexibility for modeling complex, interacting processes.
1. Everything depends on the rules we define! So it is very important to understand the rules of the game we are playing.

Discussion/brainstorm:

1. What are some possible applications of process modeling in your area of interest?

### (Lecture + discussion) What are the _constraints_ we encounter in a process modeling approach?

Key points:

1. Process models are computationally expensive! Modern computing strategies help, but high dimensionality is a serious constraint. 
1. Issues like model identifiability and correlation != causation. Just because our mechanism produces results that match some data, doesn't _necessarily_ mean our mechanism is the same mechanism that produced that data. 
1. Process models are themselves nondeterministic, so must be run many times.

### (Example) The Unified Neutral Theory of Biodiversity

Key points:

1. Hubbell's UNTB is a process model. Simply put, it is a game played with a set of simple rules, with emergent properties that we find interesting. 
1. For the rest of today, we'll be using UNTB as an example process model. 


### (Lecture + game of chance) Playing neutral theory

Key points:

1. The rules of neutral theory
1. We can play neutral theory manually. However, computers would make it considerably faster!
