# roleR and Reproducibility

## Key questions

1. How do I set up my workflow for reproducible research?
1. How do I store and share RoLE simulations?

## Lesson objectives

After this lesson, learners should be able to...

1. Describe best-practices for reproducible simulations
1. Explain why RoLE is not generally _numerically_ reproducible (yes?)
1. Describe strategies for storing and sharing code and models for works-in-progress
1. Explain the importance of and appropriate repositories for long-term archiving

## Planned exercises


## Supporting materials

_Describe, and where possible link to, lesson materials that will be needed for this section of the workshop. These could include code for live coding, code documentation, book chapters, videos/animations, etc._

_For bonus points organize these according to whether they already exist or we need to create them!_

### Extant

### To create

* Relevant chapters of user guide.

## Key points

_List 1-3 key takeaways from this section of the workshop._